<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textFieldId</name>
   <tag></tag>
   <elementGuidId>9dc32ec9-7b54-4260-87b4-36d65d6bff10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;editor&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;editor&quot;]</value>
      <webElementGuid>26692d4c-fe9d-4111-aede-a6b3266add26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
